// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFeApi.Context;

#nullable disable

namespace NFeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("NFeApi.Entities.Emitente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NFeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NFeId")
                        .IsUnique();

                    b.ToTable("Emitentes");
                });

            modelBuilder.Entity("NFeApi.Entities.ItemNFe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NFeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NFeId");

                    b.ToTable("ItensNFe");
                });

            modelBuilder.Entity("NFeApi.Entities.NFe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NFes");
                });

            modelBuilder.Entity("NFeApi.Entities.Emitente", b =>
                {
                    b.HasOne("NFeApi.Entities.NFe", "NFe")
                        .WithOne("Emitente")
                        .HasForeignKey("NFeApi.Entities.Emitente", "NFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFe");
                });

            modelBuilder.Entity("NFeApi.Entities.ItemNFe", b =>
                {
                    b.HasOne("NFeApi.Entities.NFe", "NFe")
                        .WithMany("Itens")
                        .HasForeignKey("NFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFe");
                });

            modelBuilder.Entity("NFeApi.Entities.NFe", b =>
                {
                    b.Navigation("Emitente");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
